### ISSUE TITLE
Server sent Alert instead of response

### ISSUE THREAD

**Issue by Jonas-Metzger** [tlsnotary/pagesigner#42]
I'm trying to sign the following .xml:

[https://oco2.gesdisc.eosdis.nasa.gov/data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml](https://oco2.gesdisc.eosdis.nasa.gov/data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml)

However, I get a "Server sent Alert instead of response" error, both for the browser plugin and the pgsg-node tool.
For the latter, i use the following command: 

`node pgsg-node.js notarize oco2.gesdisc.eosdis.nasa.gov --headers headers.txt`

where headers.txt looks as follows:

```
GET /data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml HTTP/1.1
Host: oco2.gesdisc.eosdis.nasa.gov


```

Any idea how to fix this? Thanks a lot!

**Comment by themighty1** [comment]
Usually from my experience the alert that the server sends is called "close notify", ie the server simply closes the connection. 
It may happen when the request doesn't containt an http header which the server  expects.

**Comment by Jonas-Metzger** [comment]
Thank you for the help! But why would the browser plugin then fail as well?

**Comment by themighty1** [comment]
Good point. Could be 2 reasons:
1) Since Chromium does not expose all http headers to the plugins  (for security reasons) maybe one of those un-exposed headers is expected by the server
2) PageSigner changes Accept-Encoding header to disable compression
here:
https://github.com/tlsnotary/pagesigner/blob/75fa750e03caba4a65f96a39d31676d4333423ea/webextension/content/main.js#L296

**Comment by Jonas-Metzger** [comment]
Hm. Opening the link in chrome -> inspect -> network -> headers -> oco3_...nc4.xml -> request headers, chrome uses:

`GET /data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml HTTP/1.1
Host: oco2.gesdisc.eosdis.nasa.gov
Connection: keep-alive
Cache-Control: max-age=0
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7
If-None-Match: "1433-5c42e854ffb70"
If-Modified-Since: Mon, 07 Jun 2021 15:16:07 GMT`

Using this as the headers.txt produces the same behavior. How would I find out which headers I am supposed to use?

**Comment by themighty1** [comment]
Could you comment out this line
https://github.com/tlsnotary/pagesigner/blob/75fa750e03caba4a65f96a39d31676d4333423ea/webextension/content/main.js#L307
i.e. make it `//h.value = '' `

This will show whether or not disabling compression is at fault.

**Comment by Jonas-Metzger** [comment]
Unfortunately that doesn't change anything. Also tried uncommenting line 306, didn't help either. :(

**Comment by Jonas-Metzger** [comment]
This is the output, in case it helps:
```
connected
0 0
0 0
0 0
0 0
0 0
Received data complete 2976
Received data incomplete 0
recv promise resolving
[
   22,   3,   3,   0,  80,   2,  0,   0,  76,   3,   3,  80,
    7, 180,  48,  93,  26, 146, 11, 138, 195, 189,  88, 189,
  139, 149, 225, 115,  76, 213, 74, 173, 194, 164,  61, 227,
  104, 147, 171,  63, 205,  62, 55,  32,  99, 114, 229, 222,
  160, 193,  58, 149, 161, 233, 63,  85,  21,  91, 226,  46,
   57, 147, 154, 112,  17, 158, 13, 226, 225, 203,  46, 210,
   78,  61, 182, 232, 192,  47,  0,   0,   4,   0,   0,   0,
    0,  22,   3,   3,   9, 235, 11,   0,   9, 231,   0,   9,
  228,   0,   5, 117,
  ... 2876 more items
]
390 jXaoEt1vJ4S1YAkjIxMJLOhOF+zkwfqHLPZFNOE1F6xvfmV6MNN+pHAIrCnGRHuBypBnuM9MW0HxmV3qlArubqzl/se4ChlKc0"}
88 
{"response": "vd", "data": "B+F1gmMKs3jysWmfNLqUlf3v6bmGwdLyzjsnO8ozljqlgITDL8i2DA=="}
0 0
0 0
0 0
Received data complete 51
Received data incomplete 0
recv promise resolving
83 
{"response": "verify_status", "data": "76RcPYEuEWn6qcugPmKi/W9LhOOmhsxJv70pgVU="}
0 0
0 0
0 0
Received data complete 543
Received data incomplete 0
Received data complete 574
Received data incomplete 0
recv promise resolving
server_reply.length 574
Server sent Alert instead of response
(node:3625) UnhandledPromiseRejectionWarning: Server sent Alert instead of response
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3625) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
```

**Comment by Jonas-Metzger** [comment]
Also, 

`wget https://oco2.gesdisc.eosdis.nasa.gov/data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml -d`

successfully downloads the .xml file and outputs:

```
DEBUG output created by Wget 1.19.4 on linux-gnu.

Reading HSTS entries from /root/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml' (UTF-8) -> 'oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml' (UTF-8)
--2021-06-14 06:14:29--  https://oco2.gesdisc.eosdis.nasa.gov/data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml
Resolving oco2.gesdisc.eosdis.nasa.gov (oco2.gesdisc.eosdis.nasa.gov)... 198.118.197.34, 2001:4d0:241a:4041::34
Caching oco2.gesdisc.eosdis.nasa.gov => 198.118.197.34 2001:4d0:241a:4041::34
Connecting to oco2.gesdisc.eosdis.nasa.gov (oco2.gesdisc.eosdis.nasa.gov)|198.118.197.34|:443... connected.
Created socket 5.
Releasing 0x0000557707a52b00 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 5 to SSL handle 0x0000557707a76000
certificate:
  subject: CN=gs6102dsc-oco2.gesdisc.eosdis.nasa.gov
  issuer:  CN=R3,O=Let's Encrypt,C=US
X509 certificate successfully verified and matches host oco2.gesdisc.eosdis.nasa.gov

---request begin---
GET /data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml HTTP/1.1
User-Agent: Wget/1.19.4 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: oco2.gesdisc.eosdis.nasa.gov
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Date: Mon, 14 Jun 2021 06:14:30 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000;includeSubdomains;
Last-Modified: Mon, 07 Jun 2021 15:16:07 GMT
ETag: "1433-5c42e854ffb70"
Accept-Ranges: bytes
Content-Length: 5171
Connection: close
Content-Type: text/xml

---response end---
200 OK
Parsed Strict-Transport-Security max-age = 31536000, includeSubDomains = true
Updated HSTS host: oco2.gesdisc.eosdis.nasa.gov:443 (max-age: 31536000, includeSubdomains: true)
Length: 5171 (5.0K) [text/xml]
Saving to: ‘oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml’

oco3_LtCO2_210405_B 100%[===================>]   5.05K  --.-KB/s    in 0s      

Closed 5/SSL 0x0000557707a76000
2021-06-14 06:14:30 (89.5 MB/s) - ‘oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml’ saved [5171/5171]

Saving HSTS entries to /root/.wget-hsts
```

**Comment by themighty1** [comment]
Ah, I see what's up. 
Please comment out this line
https://github.com/tlsnotary/pagesigner/blob/75fa750e03caba4a65f96a39d31676d4333423ea/webextension/content/tlsn.js#L374

**Comment by Jonas-Metzger** [comment]
This now outputs

```
connected
0 0
0 0
0 0
0 0
0 0
Received data complete 2976
Received data incomplete 0
recv promise resolving
[
   22,   3,   3,   0,  80,   2,   0,   0,  76,   3,   3, 159,
  138, 250, 249, 107, 220, 234, 193,  87, 139, 137, 170,  14,
  203, 203, 177,  89, 132,  27,  78, 162, 146, 186, 226, 113,
  194,  91,  88,  76, 158,  13,  71,  32, 196, 202,  18,  92,
  197,  96, 145, 201,  80, 242, 177, 167, 228, 240,  39,  80,
    5,  76, 251, 215,   8, 240, 159,  75, 140, 162, 158,  27,
  252, 152, 156,  26, 192,  47,   0,   0,   4,   0,   0,   0,
    0,  22,   3,   3,   9, 235,  11,   0,   9, 231,   0,   9,
  228,   0,   5, 117,
  ... 2876 more items
]
394 gai8+9Vbu5q465M7o8eEngO/snynd/wcgAYG4s+iZ+kr2HfyP5Lcrosy69yPPwqGDL/CZvzV7dnMYnz4gIMt5fMsuLSQ2J0J8="}
88 
{"response": "vd", "data": "ngErSAFQkkOpmBIdVn391m9qaEZtNNHp6Ljg+iefjhb8jt0o/lPdhg=="}
0 0
0 0
0 0
Received data complete 51
Received data incomplete 0
recv promise resolving
83 
{"response": "verify_status", "data": "zwWM0JS4ZpSkbUQdVxzAp3VCgHWTB+eLD/JVWLA="}
0 0
0 0
0 0
Received data complete 574
Received data incomplete 0
recv promise resolving
server_reply.length 574
Server sent Alert instead of response
214 z0RFKsJDViRb2Yf6AoZNGUArKuqZNwkP8pycuOcfszVOuHgvzQ7lmZxfBt8pngKVLuHlUPseMw2oVZDXT0Bz8Ozi/FuSt12Q=="}
server_write_key, server_write_IV [
  197, 209, 155,  93,  29,
   68, 222, 190,  37, 188,
   24, 102, 205, 226, 147,
   40
] [ 18, 35, 172, 80 ]
resp.length 96
Error: Unsupported state or unable to authenticate data
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at Function.decryptAesGCM (/content/node_modules/@peculiar/webcrypto/build/webcrypto.js:258:44)
    at Function.decrypt (/content/node_modules/@peculiar/webcrypto/build/webcrypto.js:201:29)
    at AesGcmProvider.onDecrypt (/content/node_modules/@peculiar/webcrypto/build/webcrypto.js:475:26)
    at AesGcmProvider.decrypt (/content/node_modules/webcrypto-core/build/webcrypto-core.js:176:31)
    at SubtleCrypto.decrypt (/content/node_modules/webcrypto-core/build/webcrypto-core.js:829:39)
    at decrypt_tls_responseV4 (/content/pagesigner/webextension/content/tlsn.js:576:51)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.start_audit (/content/pagesigner/webextension/content/tlsn.js:355:20)
    at async main (/content/pagesigner/webextension/content/pgsg-node/pgsg-node.js:215:14)
(node:3913) UnhandledPromiseRejectionWarning: Error
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3913) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3913) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by themighty1** [comment]
ok, i'll have to look into it closer.

**Comment by Jonas-Metzger** [comment]
Really appreciate the effort! Thank you so much.

**Comment by themighty1** [comment]
Thanks for the report @Jonas-Metzger , I just pushed a fix to the master branch.

**Comment by Jonas-Metzger** [comment]
Awesome, thanks! It does generate .pgsg files now!
Unfortunately, the generated cleartext does not correspond to the .xml. Instead, it reads:

```
HTTP/1.1 400 Bad Request
Date: Mon, 14 Jun 2021 07:19:52 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000;includeSubdomains;
Content-Length: 226
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

even though I used the exact same header used by wget:


```
GET /data/OCO3_DATA/OCO3_L2_Lite_FP.EarlyR/2021/oco3_LtCO2_210405_B10205Xr_210602184241s.nc4.xml HTTP/1.1
User-Agent: Wget/1.19.4 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: oco2.gesdisc.eosdis.nasa.gov


```

**Comment by themighty1** [comment]
Try to comment out //h.value = ''  "

**Comment by themighty1** [comment]
I mean change it to //h.value = '' "

**Comment by Jonas-Metzger** [comment]
Changes nothing :(

**Comment by themighty1** [comment]
@Jonas-Metzger , thanks again, it was a bug in pgsg-node. now fixed in master.

**Comment by Jonas-Metzger** [comment]
It works now!!! I really appreciate your effort, thank you so much!
